version: '3.8'

volumes:
  pgdata:

networks:
  kube-news_net:
    name: kube-news_net
    driver: bridge

services:
  kube-news:
    image: kube-news
    container_name: kube-news2
    build:
      dockerfile: ./Dockerfile
      context: ./
    networks: 
    - kube-news_net
    ports:
    - 8080:8080
    depends_on:
      - postgres
    environment:
      DB_DATABASE: kubedevnews
      DB_USERNAME: kubedevnews
      DB_PASSWORD: Pg#123
      DB_HOST: postgres

  postgres:
    image: postgres:14.5
    container_name: postgres
    networks:
    - kube-news_net
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: Pg#123
      POSTGRES_USER: kubedevnews
      POSTGRES_DB: kubedevnews
  
  pgadmin:
    image: dpage/pgadmin4:6.13
    container_name: pgadmin4
    ports:
      - 80:80
    networks:
      - kube-news_net
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_PASSWORD: kubedevnews
      PGADMIN_DEFAULT_EMAIL: admin@admin.com