version: "3.9"
services:
  maria:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: mydatabase
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
    networks:
      - maria-network
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: maria
      PMA_USER: admin
      PMA_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8080:80
    networks:
      - maria-network

networks:
  maria-network:
    driver: bridge